"""sra audit alternative modes — whole-repo, single-invocation flows.

Each mode in this module is a complement to the default ``sra audit``
pipeline. The default audit composes deterministic sensor + packet
stages and per-packet skill invocations. The modes here skip that
entirely: they load **one** Trail of Bits SKILL.md, assemble a
mode-specific extra-context block (a diff summary, a spec document,
a test-layout snapshot), pipe the bundle into ``claude -p``, and
write the result under ``<repo>/.audit/05-report/``.

The four modes (registered in :mod:`sra.skill_registry` with
``stage="alt-mode"`` / ``trigger="per-mode"``):

* ``differential``           -> ``differential-review`` skill
* ``spec-to-code``           -> ``spec-to-code-compliance`` skill
* ``mutation-testing``       -> ``mutation-testing`` skill
* ``property-based-testing`` -> ``property-based-testing`` skill

These are dispatched from ``sra.cli.main`` when ``--mode`` is set to
anything other than ``audit``. The default ``audit`` mode continues
to call ``sra.cli.cmd_audit`` untouched.

Design notes (Phase 6):

* These modes don't have packet builders or families - they're
  whole-repo single-invocation flows. The skill is responsible for
  the comparison logic; we only feed it a small structured hint.
* The differential summary is intentionally naive: file-level
  added / removed / common, plus a per-file byte-size delta. It's a
  navigation hint for the skill, not a precise diff. If both
  repos share a git history, ``--diff-tool git`` swaps in
  ``git diff --stat`` output instead.
* The spec read is whole-file, capped at 50 KB (the skill is
  responsible for chunking it further if needed).
* For mutation / property modes, we surface the repo's test
  directory layout, a count of test files, and short excerpts
  from a few of them so the skill has something concrete to
  reason about.
* ``--no-skills`` is rejected by the CLI dispatcher with a clear
  error: the alt-mode skills *are* the entire mode. Skipping
  them means doing nothing, which is more useful as an explicit
  failure than a silent no-op.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from sra.skill_loader import load_skill_prompt


# Directories the file walker never descends into. Mirrors
# ``sra.cli.SKIP_DIRECTORIES`` — kept in sync by hand because importing
# from cli.py would create a cycle (cli imports this module).
_SKIP_DIRECTORIES: set[str] = {
    ".git", ".hg", ".svn",
    "node_modules", "bower_components", "vendor",
    "__pycache__", ".venv", "venv", "env",
    ".tox", ".nox",
    ".mypy_cache", ".pytest_cache", ".ruff_cache",
    "dist", "build", "target", "out",
    ".idea", ".vscode", ".vs",
    ".gradle", ".next", ".nuxt", ".svelte-kit",
    ".audit",
}


# Conservative cap for the spec file fed into spec-to-code-compliance.
# The skill is responsible for further chunking; we just guarantee a
# single invocation does not blow up the prompt.
_SPEC_MAX_BYTES = 50 * 1024


# Cap how many files we list in the diff summary buckets. The skill
# treats this as a navigation hint, not a precise inventory.
_DIFF_MAX_FILES_PER_BUCKET = 200


# Cap how many test files we excerpt for mutation / property modes.
_TEST_SAMPLE_LIMIT = 5
_TEST_EXCERPT_LINES = 40


# Conventional test-directory basenames (lowercased) the walkers look
# for. Matches the role group in ``sra.cli.DIRECTORY_ROLE_NAMES``.
_TEST_DIR_NAMES: set[str] = {
    "tests", "test", "spec", "specs", "regression", "__tests__",
}


# =========================================================================
# Shared helpers
# =========================================================================

def _now_iso() -> str:
    """Return current UTC time as an ISO-8601 timestamp (no microseconds)."""
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _attribution_header(skill_name: str, mode: str, repo: Path) -> str:
    """Return a markdown header that credits the Trail of Bits skill."""
    return (
        f"# {mode} mode — {skill_name}\n"
        f"\n"
        f"_Generated by `sra audit --mode {mode}` on {_now_iso()}._\n"
        f"\n"
        f"_Target repo: `{repo}`_\n"
        f"\n"
        f"_Skill: Trail of Bits `{skill_name}` (CC-BY-SA-4.0). "
        f"See `LICENSE_THIRD_PARTY.md` for attribution. The text below "
        f"is the model's response; the skill text itself is not copied "
        f"into this report._\n"
        f"\n"
        f"---\n"
        f"\n"
    )


def _collect_repo_files(repo: Path, max_files: int = 5000) -> list[str]:
    """Walk ``repo`` and return relative POSIX file paths, deterministically ordered.

    Skips ``_SKIP_DIRECTORIES`` and stops at ``max_files`` to keep the
    diff payload bounded. The order is the OS walk order sorted, so
    successive calls on the same tree produce the same list.
    """
    files: list[str] = []
    for dirpath, dirnames, filenames in os.walk(repo):
        # in-place filter so the walker doesn't descend into skips
        dirnames[:] = sorted(d for d in dirnames if d not in _SKIP_DIRECTORIES)
        rel_dir = os.path.relpath(dirpath, repo)
        for fn in sorted(filenames):
            rel = fn if rel_dir == "." else f"{rel_dir}/{fn}"
            files.append(rel.replace(os.sep, "/"))
            if len(files) >= max_files:
                return files
    return files


def _read_existing_report(repo: Path) -> str | None:
    """Return the contents of ``<repo>/.audit/05-report/repo-report.md`` if present."""
    p = repo / ".audit" / "05-report" / "repo-report.md"
    if not p.is_file():
        return None
    try:
        return p.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


def _find_test_dirs(repo: Path) -> list[Path]:
    """Return absolute paths to any conventional test directories under ``repo``."""
    out: list[Path] = []
    for dirpath, dirnames, _ in os.walk(repo):
        dirnames[:] = [d for d in dirnames if d not in _SKIP_DIRECTORIES]
        for d in list(dirnames):
            if d.lower() in _TEST_DIR_NAMES:
                out.append(Path(dirpath) / d)
        # Stop descent inside test dirs themselves — we only want the
        # outermost test roots, the listing below walks them fully.
        dirnames[:] = [d for d in dirnames if d.lower() not in _TEST_DIR_NAMES]
    return sorted(out)


def _count_test_files(test_dirs: list[Path]) -> tuple[int, list[Path]]:
    """Walk each test dir; return (total_count, sample[]) of test source files.

    "Test source" is heuristic: any file under a test dir whose extension is
    one of {.py, .js, .ts, .tsx, .jsx, .go, .rs, .java, .rb, .php, .c, .cpp,
    .h, .hpp, .swift, .kt, .scala, .ex, .exs}. The sample is up to
    ``_TEST_SAMPLE_LIMIT`` files, drawn in walk order.
    """
    exts = {
        ".py", ".js", ".ts", ".tsx", ".jsx", ".go", ".rs", ".java",
        ".rb", ".php", ".c", ".cpp", ".h", ".hpp", ".swift", ".kt",
        ".scala", ".ex", ".exs",
    }
    total = 0
    sample: list[Path] = []
    for root in test_dirs:
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = [d for d in dirnames if d not in _SKIP_DIRECTORIES]
            for fn in sorted(filenames):
                ext = Path(fn).suffix.lower()
                if ext in exts:
                    total += 1
                    if len(sample) < _TEST_SAMPLE_LIMIT:
                        sample.append(Path(dirpath) / fn)
    return total, sample


def _excerpt(path: Path, max_lines: int = _TEST_EXCERPT_LINES) -> str:
    """Return up to ``max_lines`` lines of ``path``, or empty on read error."""
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            return "".join(line for _, line in zip(range(max_lines), fh))
    except OSError:
        return ""


# =========================================================================
# Differential summary
# =========================================================================

def _diff_summary(repo_a: Path, repo_b: Path) -> str:
    """Build a markdown block describing the file-level delta between two trees.

    Output structure:

      * Added (in repo_b, not in repo_a) — up to N entries
      * Removed (in repo_a, not in repo_b) — up to N entries
      * Common (in both)                  — count + total byte delta
      * Sample of common files with the largest byte delta
    """
    a_files = _collect_repo_files(repo_a)
    b_files = _collect_repo_files(repo_b)
    a_set = set(a_files)
    b_set = set(b_files)

    added = sorted(b_set - a_set)
    removed = sorted(a_set - b_set)
    common = sorted(a_set & b_set)

    def _bullet_list(items: list[str], cap: int) -> str:
        if not items:
            return "_(none)_\n"
        capped = items[:cap]
        rest = len(items) - len(capped)
        lines = "\n".join(f"- `{p}`" for p in capped)
        if rest > 0:
            lines += f"\n- _… and {rest} more_"
        return lines + "\n"

    a_bytes_total = 0
    b_bytes_total = 0
    sample_changed: list[tuple[str, int, int]] = []
    for rel in common[:1000]:  # cap to keep this fast on huge repos
        a_path = repo_a / rel
        b_path = repo_b / rel
        try:
            a_size = a_path.stat().st_size
            b_size = b_path.stat().st_size
        except OSError:
            continue
        a_bytes_total += a_size
        b_bytes_total += b_size
        if a_size != b_size:
            sample_changed.append((rel, a_size, b_size))

    sample_changed.sort(key=lambda t: abs(t[1] - t[2]), reverse=True)
    sample_lines = (
        "\n".join(
            f"- `{rel}` ({a} -> {b} bytes, delta {b - a:+d})"
            for rel, a, b in sample_changed[:_DIFF_MAX_FILES_PER_BUCKET]
        )
        or "_(no size-changed common files detected)_"
    )

    return (
        f"## Differential summary (naive)\n"
        f"\n"
        f"This is a file-level navigation hint, not a precise diff.\n"
        f"The skill is responsible for inspecting individual files.\n"
        f"\n"
        f"- repo_a: `{repo_a}` ({len(a_files)} files)\n"
        f"- repo_b: `{repo_b}` ({len(b_files)} files)\n"
        f"- common: {len(common)} files "
        f"({a_bytes_total} -> {b_bytes_total} bytes, "
        f"delta {b_bytes_total - a_bytes_total:+d})\n"
        f"\n"
        f"### Added (only in repo_b)\n"
        f"\n"
        f"{_bullet_list(added, _DIFF_MAX_FILES_PER_BUCKET)}"
        f"\n"
        f"### Removed (only in repo_a)\n"
        f"\n"
        f"{_bullet_list(removed, _DIFF_MAX_FILES_PER_BUCKET)}"
        f"\n"
        f"### Common files with size delta\n"
        f"\n"
        f"{sample_lines}\n"
    )


def _git_diff_stat(repo_a: Path, repo_b: Path) -> str | None:
    """If both paths are inside a git worktree, return ``git diff --stat`` output.

    Best-effort and naive: runs ``git diff --stat`` inside ``repo_a``
    only when both paths have a ``.git`` entry of their own. Returns
    ``None`` if anything goes wrong (the caller falls back to
    :func:`_diff_summary`).
    """
    git = shutil.which("git")
    if not git:
        return None
    if not (repo_a / ".git").exists() or not (repo_b / ".git").exists():
        return None
    try:
        proc = subprocess.run(
            [git, "diff", "--stat", "--no-color"],
            cwd=str(repo_a),
            capture_output=True, text=True,
            encoding="utf-8", errors="replace",
            timeout=60,
        )
    except (subprocess.TimeoutExpired, OSError):
        return None
    if proc.returncode != 0:
        return None
    out = proc.stdout or ""
    if not out.strip():
        return "## git diff --stat\n\n_(empty — working tree clean on repo_a)_\n"
    return f"## git diff --stat (run inside repo_a)\n\n```\n{out}\n```\n"


# =========================================================================
# Repo structure / test-layout summaries
# =========================================================================

def _repo_structure_summary(repo: Path) -> str:
    """Tiny markdown snapshot: file count, top extensions, top-level dirs."""
    files = _collect_repo_files(repo)
    ext_counts: dict[str, int] = {}
    for f in files:
        ext = Path(f).suffix.lower()
        ext_counts[ext] = ext_counts.get(ext, 0) + 1
    top_exts = sorted(ext_counts.items(), key=lambda kv: -kv[1])[:10]
    top_dirs: list[str] = []
    try:
        for entry in sorted(repo.iterdir()):
            if entry.is_dir() and entry.name not in _SKIP_DIRECTORIES:
                top_dirs.append(entry.name)
    except OSError:
        pass
    return (
        f"## Repo structure snapshot\n"
        f"\n"
        f"- root: `{repo}`\n"
        f"- file count: {len(files)} (capped at 5000)\n"
        f"- top extensions: "
        + ", ".join(f"{ext or '<none>'}={n}" for ext, n in top_exts)
        + "\n"
        f"- top-level directories: "
        + ", ".join(f"`{d}`" for d in top_dirs[:20])
        + "\n"
    )


def _test_layout_summary(repo: Path, *, emphasis: str = "tests") -> str:
    """Markdown block describing the repo's test directory layout.

    ``emphasis`` is woven into the prose so the skill downstream knows
    which kind of test artefact the mode cares about (``mutation`` vs
    ``property-based``).
    """
    test_dirs = _find_test_dirs(repo)
    if not test_dirs:
        return (
            f"## Test layout ({emphasis})\n"
            f"\n"
            f"_No conventional test directory found_ "
            f"(searched basenames: {sorted(_TEST_DIR_NAMES)}).\n"
            f"The skill should report this as a coverage gap.\n"
        )
    total, sample = _count_test_files(test_dirs)
    rel_dirs = [str(d.relative_to(repo)).replace(os.sep, "/") for d in test_dirs]
    excerpts: list[str] = []
    for s in sample:
        rel = str(s.relative_to(repo)).replace(os.sep, "/")
        text = _excerpt(s)
        if not text:
            continue
        excerpts.append(
            f"#### `{rel}` (first {_TEST_EXCERPT_LINES} lines)\n\n"
            f"```\n{text.rstrip()}\n```\n"
        )
    excerpts_md = "\n".join(excerpts) if excerpts else "_(no excerpts available)_\n"
    return (
        f"## Test layout ({emphasis})\n"
        f"\n"
        f"- test directories ({len(test_dirs)}): "
        + ", ".join(f"`{d}`" for d in rel_dirs)
        + "\n"
        f"- total test files (heuristic, by extension): {total}\n"
        f"- sampling up to {_TEST_SAMPLE_LIMIT} files for excerpts below\n"
        f"\n"
        f"### Sample test excerpts\n"
        f"\n"
        f"{excerpts_md}"
    )


# =========================================================================
# Claude invocation
# =========================================================================

def _invoke_claude(
    prompt: str, *, repo_cwd: Path, model: str | None,
    timeout: int = 3600,
) -> tuple[int, str, str]:
    """Pipe ``prompt`` into ``claude -p``, return (rc, stdout, stderr).

    Mirrors the nested-session guard used elsewhere in the project
    (clears ``CLAUDECODE`` / ``CLAUDE_CODE_ENTRYPOINT``). Uses
    ``repo_cwd`` as the working directory so Read/Grep tools resolve
    against the target.

    Routes via ``cli._run_claude_with_heartbeat`` so the live child is
    tracked in the project-wide ``_LIVE_PROCS`` registry and the user
    can stop the run with Ctrl+C. Default timeout raised to 3600s
    (1 h) — alt-modes run a single whole-repo pass and 20 min was
    routinely too short.
    """
    claude = shutil.which("claude")
    if not claude:
        return 127, "", "`claude` CLI not found on PATH"

    env = os.environ.copy()
    env.pop("CLAUDECODE", None)
    env.pop("CLAUDE_CODE_ENTRYPOINT", None)

    cmd = [claude, "-p"]
    if model:
        cmd.extend(["--model", model])

    # Import lazily to avoid circular import (cli.py imports this module).
    from sra.cli import _run_claude_with_heartbeat
    try:
        proc = _run_claude_with_heartbeat(
            cmd, input_text=prompt, timeout=timeout,
            cwd=str(repo_cwd), env=env,
            label=f"audit-mode [{model}]" if model else "audit-mode",
        )
    except subprocess.TimeoutExpired:
        return 124, "", f"claude -p timed out after {timeout} s"
    except KeyboardInterrupt:
        return 130, "", "interrupted by user"

    return proc.returncode, proc.stdout or "", proc.stderr or ""


def _write_output(out_path: Path, header: str, body: str, stderr: str) -> int:
    """Write ``header`` + ``body`` (+ stderr if present) to ``out_path``.

    Atomic write (temp file + os.replace) so an interrupt mid-write
    leaves the previous output (or nothing) intact rather than a
    truncated artefact masquerading as a finished report.

    Returns 0 on success, 1 on write failure. Parent dirs are created.
    """
    try:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        combined = header + body
        if stderr:
            combined += (
                f"\n\n---\n\n## stderr from claude -p\n\n"
                f"```\n{stderr.rstrip()}\n```\n"
            )
        tmp = out_path.with_suffix(out_path.suffix + ".tmp")
        tmp.write_text(combined, encoding="utf-8")
        os.replace(tmp, out_path)
    except OSError as e:
        print(f"error: cannot write {out_path}: {e}", file=sys.stderr)
        return 1
    return 0


def _ensure_dir(repo_str: str) -> Path | None:
    """Resolve and validate a repo path. Returns ``None`` after printing on error."""
    p = Path(repo_str).expanduser()
    if not p.is_dir():
        print(f"error: not a directory: {p}", file=sys.stderr)
        return None
    return p.resolve()


# =========================================================================
# Mode entry points
# =========================================================================

def cmd_audit_mode_differential(
    repo_a_str: str,
    repo_b_str: str,
    *,
    diff_tool: str | None = None,
    model: str | None = None,
) -> int:
    """``sra audit <repo_a> --mode differential --repo-b <repo_b>``.

    Loads the ToB ``differential-review`` skill, computes a naive
    file-level diff summary between the two repos (optionally
    augmented with ``git diff --stat`` when ``diff_tool='git'``),
    pulls in any existing ``.audit/05-report/repo-report.md`` from
    either side, pipes the bundle into ``claude -p``, and writes
    the response to
    ``<repo_a>/.audit/05-report/differential-vs-<repo_b_name>.md``.
    """
    repo_a = _ensure_dir(repo_a_str)
    if repo_a is None:
        return 2
    repo_b = _ensure_dir(repo_b_str)
    if repo_b is None:
        return 2

    print(f"[mode differential] repo_a={repo_a}", file=sys.stderr)
    print(f"[mode differential] repo_b={repo_b}", file=sys.stderr)

    diff_block = _diff_summary(repo_a, repo_b)
    git_block = _git_diff_stat(repo_a, repo_b) if diff_tool == "git" else None

    extra: list[str] = [diff_block]
    if git_block:
        extra.append(git_block)
    rep_a = _read_existing_report(repo_a)
    if rep_a:
        extra.append(f"## Existing repo-report.md from repo_a\n\n{rep_a}")
    rep_b = _read_existing_report(repo_b)
    if rep_b:
        extra.append(f"## Existing repo-report.md from repo_b\n\n{rep_b}")
    extra.append(
        f"## Task\n\n"
        f"Apply the **differential-review** skill above to the change "
        f"from repo_a ({repo_a}) to repo_b ({repo_b}). Use the file-level "
        f"summary above as navigation. Open individual files with Read / "
        f"Grep / Glob as needed. Produce the comprehensive markdown report "
        f"the skill prescribes. Output only the report text — no preamble."
    )

    prompt = load_skill_prompt("differential-review", extra_context=extra)

    rc, stdout, stderr = _invoke_claude(prompt, repo_cwd=repo_a, model=model)
    out_path = (
        repo_a / ".audit" / "05-report" / f"differential-vs-{repo_b.name}.md"
    )
    header = _attribution_header("differential-review", "differential", repo_a)
    write_rc = _write_output(out_path, header, stdout, stderr)
    if write_rc != 0:
        return write_rc

    if rc != 0:
        print(
            f"[mode differential] claude -p returned {rc}; partial output "
            f"written to {out_path}",
            file=sys.stderr,
        )
        return rc
    print(f"[mode differential] wrote {out_path}", file=sys.stderr)
    return 0


def cmd_audit_mode_spec_to_code(
    repo_str: str,
    spec_path_str: str,
    *,
    model: str | None = None,
) -> int:
    """``sra audit <repo> --mode spec-to-code --spec <spec.md>``.

    Loads the ToB ``spec-to-code-compliance`` skill, reads the spec
    document (whole file, capped at 50 KB), attaches a small repo
    structure snapshot, and writes the model's response to
    ``<repo>/.audit/05-report/spec-compliance.md``.
    """
    repo = _ensure_dir(repo_str)
    if repo is None:
        return 2
    spec_path = Path(spec_path_str).expanduser().resolve()
    if not spec_path.is_file():
        print(f"error: spec file not found: {spec_path}", file=sys.stderr)
        return 2

    try:
        spec_text = spec_path.read_bytes()[:_SPEC_MAX_BYTES].decode(
            "utf-8", errors="replace"
        )
    except OSError as e:
        print(f"error: cannot read spec {spec_path}: {e}", file=sys.stderr)
        return 2
    truncated = spec_path.stat().st_size > _SPEC_MAX_BYTES

    print(f"[mode spec-to-code] repo={repo}", file=sys.stderr)
    print(f"[mode spec-to-code] spec={spec_path}", file=sys.stderr)

    spec_block = (
        f"## Specification document ({spec_path.name})\n"
        f"\n"
        + (
            f"_(truncated to first {_SPEC_MAX_BYTES} bytes)_\n\n"
            if truncated else ""
        )
        + f"```\n{spec_text.rstrip()}\n```\n"
    )

    extra: list[str] = [
        spec_block,
        _repo_structure_summary(repo),
        (
            f"## Task\n\n"
            f"Apply the **spec-to-code-compliance** skill above. Compare "
            f"the codebase at `{repo}` against the spec above. Use Read / "
            f"Grep / Glob to verify each requirement of the spec is "
            f"actually implemented (and implemented correctly). Produce "
            f"the markdown compliance report the skill prescribes."
        ),
    ]

    prompt = load_skill_prompt("spec-to-code-compliance", extra_context=extra)

    rc, stdout, stderr = _invoke_claude(prompt, repo_cwd=repo, model=model)
    out_path = repo / ".audit" / "05-report" / "spec-compliance.md"
    header = _attribution_header(
        "spec-to-code-compliance", "spec-to-code", repo,
    )
    write_rc = _write_output(out_path, header, stdout, stderr)
    if write_rc != 0:
        return write_rc

    if rc != 0:
        print(
            f"[mode spec-to-code] claude -p returned {rc}; partial output "
            f"written to {out_path}",
            file=sys.stderr,
        )
        return rc
    print(f"[mode spec-to-code] wrote {out_path}", file=sys.stderr)
    return 0


def cmd_audit_mode_mutation_testing(
    repo_str: str,
    *,
    model: str | None = None,
) -> int:
    """``sra audit <repo> --mode mutation-testing``.

    Loads the ToB ``mutation-testing`` skill, attaches a snapshot of
    the repo's test directory layout (including a count and a few
    excerpts), and writes the response to
    ``<repo>/.audit/05-report/mutation-testing.md``.
    """
    repo = _ensure_dir(repo_str)
    if repo is None:
        return 2

    print(f"[mode mutation-testing] repo={repo}", file=sys.stderr)

    extra: list[str] = [
        _repo_structure_summary(repo),
        _test_layout_summary(repo, emphasis="mutation"),
        (
            f"## Task\n\n"
            f"Apply the **mutation-testing** skill above to the codebase "
            f"at `{repo}`. Assess the test suite from a mutation-testing "
            f"lens: which mutations would survive (i.e. which test gaps "
            f"exist), and which assertion patterns are too weak to catch "
            f"realistic faults. Produce the markdown report the skill "
            f"prescribes."
        ),
    ]

    prompt = load_skill_prompt("mutation-testing", extra_context=extra)

    rc, stdout, stderr = _invoke_claude(prompt, repo_cwd=repo, model=model)
    out_path = repo / ".audit" / "05-report" / "mutation-testing.md"
    header = _attribution_header("mutation-testing", "mutation-testing", repo)
    write_rc = _write_output(out_path, header, stdout, stderr)
    if write_rc != 0:
        return write_rc

    if rc != 0:
        print(
            f"[mode mutation-testing] claude -p returned {rc}; partial "
            f"output written to {out_path}",
            file=sys.stderr,
        )
        return rc
    print(f"[mode mutation-testing] wrote {out_path}", file=sys.stderr)
    return 0


def cmd_audit_mode_property_based_testing(
    repo_str: str,
    *,
    model: str | None = None,
) -> int:
    """``sra audit <repo> --mode property-based-testing``.

    Loads the ToB ``property-based-testing`` skill, attaches the
    test-layout snapshot with property-testing emphasis, and writes
    the response to
    ``<repo>/.audit/05-report/property-based-testing.md``.
    """
    repo = _ensure_dir(repo_str)
    if repo is None:
        return 2

    print(f"[mode property-based-testing] repo={repo}", file=sys.stderr)

    extra: list[str] = [
        _repo_structure_summary(repo),
        _test_layout_summary(repo, emphasis="property-based"),
        (
            f"## Task\n\n"
            f"Apply the **property-based-testing** skill above to the "
            f"codebase at `{repo}`. Identify functions whose contracts "
            f"are suited to property-based testing (idempotence, "
            f"inverses, invariants, round-trips), call out where the "
            f"existing test suite uses only example-based tests for them, "
            f"and propose concrete property tests. Produce the markdown "
            f"report the skill prescribes."
        ),
    ]

    prompt = load_skill_prompt("property-based-testing", extra_context=extra)

    rc, stdout, stderr = _invoke_claude(prompt, repo_cwd=repo, model=model)
    out_path = repo / ".audit" / "05-report" / "property-based-testing.md"
    header = _attribution_header(
        "property-based-testing", "property-based-testing", repo,
    )
    write_rc = _write_output(out_path, header, stdout, stderr)
    if write_rc != 0:
        return write_rc

    if rc != 0:
        print(
            f"[mode property-based-testing] claude -p returned {rc}; "
            f"partial output written to {out_path}",
            file=sys.stderr,
        )
        return rc
    print(f"[mode property-based-testing] wrote {out_path}", file=sys.stderr)
    return 0
